export const healthItems = [
  { id: 1, value: 'Alcohol-free', },
  { id: 2, value: 'Celery-free', },
  { id: 4, value: 'Dairy-free', },
  { id: 5, value: 'Crustacean-free', },
  { id: 6, value: 'Egg-free', },
  { id: 7, value: 'Fish-free', },
  { id: 8, value: 'Gluten-free', },
  { id: 9, value: 'Keto', },
  { id: 10, value: 'Kidney friedly', },
  { id: 11, value: 'Kosher', },
  { id: 12, value: 'Low potassium', },
  { id: 13, value: 'Lupine-free', },
  { id: 14, value: 'Mustard-free', },
  { id: 15, value: 'No oil added', },
  { id: 16, value: 'No-sugar', },
  { id: 17, value: 'Paleo', },
  { id: 18, value: 'Paleo-free', },
  { id: 19, value: 'Peanut-free', },
  { id: 20, value: 'Pescatarian', },
  { id: 21, value: 'Pork-free', },
  { id: 22, value: 'Red meat-free', },
  { id: 23, value: 'Sesame-free', },
  { id: 24, value: 'Shellfish-free', },
  { id: 25, value: 'Soy-free', },
  { id: 26, value: 'Sugar-conscious', },
  { id: 27, value: 'Tree-Nut-free', },
  { id: 28, value: 'Vegan', },
  { id: 29, value: 'Vegetarian', },
  { id: 30, value: 'Wheat-free', },
];

export const dietItems = [
  { id: 1, value: 'Balanced' },
  { id: 2, value: 'High-Fiber' },
  { id: 3, value: 'High-Protein' },
  { id: 4, value: 'Low-Carb' },
  { id: 5, value: 'Low-Fat' },
  { id: 6, value: 'Low-Sodium' },
]

export const nutrientItems = [
  { id: 1, value: "Calcium"},
  { id: 2, value: "Carbs"},
  { id: 3, value: "Cholesterol"},
  { id: 4, value: "Monounsaturated"},
  { id: 5, value: "Polyunsaturated"},
  { id: 6, value: "Saturated"},
  { id: 7, value: "Fat"},
  { id: 8, value: "Trans"},
  { id: 9, value: "Iron"},
  { id: 10, value: "Fiber"},
  { id: 11, value: "Folate (Equivalent)"},
  { id: 12, value: "Potassium"},
  { id: 13, value: "Magnesium"},
  { id: 14, value: "Sodium"},
  { id: 15, value: "Niacin (B3)"},
  { id: 16, value: "Phosphorus"},
  { id: 17, value: "Protein"},
  { id: 18, value: "Riboflavin (B2)"},
  { id: 19, value: "Sugars"},
  { id: 20, value: "Thiamin (B1)"},
  { id: 21, value: "Vitamin E"},
  { id: 22, value: "Vitamin A"},
  { id: 23, value: "Vitamin B12"},
  { id: 24, value: "Vitamin B6"},
  { id: 25, value: "Vitamin C"},
  { id: 26, value: "Vitamin D"},
  { id: 27, value: "Vitamin K"},
]
