export const healthItems = [
  { id: 1, value: 'alcohol-free', },
  { id: 2, value: 'vegan', },
  { id: 3, value: 'vegetarian', },
  { id: 4, value: 'sugar-conscious', },
  { id: 5, value: 'peanut-free', },
  { id: 6, value: 'tree-nut-free', },
];

export const dietItems = [
  { id: 7, value: 'balanced' },
  { id: 8, value: 'high-fiber' },
  { id: 9, value: 'high-protein' },
  { id: 10, value: 'low-carb' },
  { id: 11, value: 'low-fat' },
  { id: 12, value: 'low-sodium' },
]

export const nutrientItems = [
  { id: 1, value: "Calcium"},
  { id: 2, value: "Carbs"},
  { id: 3, value: "Cholesterol"},
  { id: 4, value: "Monounsaturated"},
  { id: 5, value: "Polyunsaturated"},
  { id: 6, value: "Saturated"},
  { id: 7, value: "Fat"},
  { id: 8, value: "Trans"},
  { id: 9, value: "Iron"},
  { id: 10, value: "Fiber"},
  { id: 11, value: "Folate (Equivalent)"},
  { id: 12, value: "Potassium"},
  { id: 13, value: "Magnesium"},
  { id: 14, value: "Sodium"},
  { id: 15, value: "Niacin (B3)"},
  { id: 16, value: "Phosphorus"},
  { id: 17, value: "Protein"},
  { id: 18, value: "Riboflavin (B2)"},
  { id: 19, value: "Sugars"},
  { id: 20, value: "Thiamin (B1)"},
  { id: 21, value: "Vitamin E"},
  { id: 22, value: "Vitamin A"},
  { id: 23, value: "Vitamin B12"},
  { id: 24, value: "Vitamin B6"},
  { id: 25, value: "Vitamin C"},
  { id: 26, value: "Vitamin D"},
  { id: 27, value: "Vitamin K"},
]
